# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../test_nbs/concurrent/remote/test_ProxyNode_0.ipynb.

# %% auto 0
__all__ = ['main']

# %% ../../../test_nbs/concurrent/remote/test_ProxyNode_0.ipynb 2
import asyncio, os
from fbdev.dev_utils import is_in_repl
from fbdev.graph.net import NodeSpec
from fbdev.concurrent.remote import ProxyNode
from _test_ProxyNode_0 import FooComponent

# %% ../../../test_nbs/concurrent/remote/test_ProxyNode_0.ipynb 3
async def main():
    node_spec = NodeSpec(FooComponent)
    proxy_node = ProxyNode(node_spec, parent_net=None)

    await proxy_node.task_manager.exec_coros(proxy_node.start())
    await proxy_node.task_manager.exec_coros(proxy_node.ports.input.inp.put_value('Hello child!'))
    val = await proxy_node.task_manager.exec_coros(proxy_node.ports.output.out.get_and_consume())
    assert val == 'Hey parent!'
    print("Message from child:", val)
    await proxy_node.task_manager.exec_coros(asyncio.sleep(0.5))
    await proxy_node.task_manager.exec_coros(proxy_node.stop())
    
if not is_in_repl():
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    asyncio.run(main())
