# AUTOGENERATED! DO NOT EDIT! File to edit: ../../test_nbs/comp/test_component_factory_0.ipynb.

# %% auto 0
__all__ = ['comp', 'comp_process', 'MyComponentFactory']

# %% ../../test_nbs/comp/test_component_factory_0.ipynb 1
from typing import Type, Any
from fbdev.comp import BaseComponent

# %% ../../test_nbs/comp/test_component_factory_0.ipynb 2
class MyComponentFactory(BaseComponent):    
    is_factory = True

    @classmethod
    def create_component(cls, my_attr) -> Type[BaseComponent]:
        return cls._create_component_class(class_attrs={
            'my_attr' : my_attr
        })
    
    async def _post_start(self):
        print(self.my_attr)
        
comp = MyComponentFactory.create_component('hello world')
print('Component:', comp.__name__)
comp_process = comp()
 
await comp_process.start()
await comp_process.stop()
