# AUTOGENERATED! DO NOT EDIT! File to edit: ../../test_nbs/comp/test_component_factory_1.ipynb.

# %% auto 0
__all__ = ['test']

# %% ../../test_nbs/comp/test_component_factory_1.ipynb 2
from _test_component_factory_1 import comp_with_module_set, comp_without_module_set

# %% ../../test_nbs/comp/test_component_factory_1.ipynb 3
def test():
    assert comp_with_module_set.__module__ == '_test_component_factory_1'
    assert comp_without_module_set.__module__ == 'abc'
