"""TODO fill in description"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/api/03_complib/02_job_handler_factory.ipynb.

# %% auto 0
__all__ = ['JobHandlerFactory']

# %% ../../nbs/api/03_complib/02_job_handler_factory.ipynb 4
import asyncio
import inspect
import typing
from typing import Callable, Any

import fbdev
from ..comp.packet import Packet
from ..comp.port import PortType, PortSpec, PortSpecCollection
from ..comp.base_component import BaseComponent
from . import ExecComponent
from ..graph.graph_component import GraphComponentFactory

# %% ../../nbs/api/03_complib/02_job_handler_factory.ipynb 7
class JobHandlerFactory(GraphComponentFactory):
    # job_blueprint: GraphSpec
    # active_graph: GraphSpec
    pass
