# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fbdev',
                'doc_host': 'https://lukastk.github.io',
                'git_url': 'https://github.com/lukastk/fbdev',
                'lib_path': 'fbdev'},
  'syms': {'fbdev.core': {'fbdev.core.foo': ('core.html#foo', 'fbdev/core.py')}}}
