# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/api/edge.ipynb.

# %% auto 0
__all__ = ['Edge']

# %% ../nbs/api/edge.ipynb 5
import asyncio
from typing import Type

from . import Packet
from .packet_container import DequePacketContainer
from .utils import StateHandler

# %% ../nbs/api/edge.ipynb 6
__all__ = ['Edge']

# %% ../nbs/api/edge.ipynb 7
class Edge(DequePacketContainer):
    def __init__(self,
                 maxsize:int,
                 input_node,
                 output_node):
        super().__init__(maxsize)
        self._input_node = input_node
        self._output_node = output_node
        
        self.enabled = StateHandler(True)
