# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/api/packet.ipynb.

# %% auto 0
__all__ = ['Packet']

# %% ../nbs/api/packet.ipynb 4
import asyncio

# %% ../nbs/api/packet.ipynb 5
__all__ = ['Packet']

# %% ../nbs/api/packet.ipynb 6
class Packet:
    def __init__(self, data):
        self.data = data
        self.dtype = type(data)
        
    def get_data(self):
        return self.data
