"""TODO fill in description"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/api/00_packet.ipynb.

# %% auto 0
__all__ = ['NullPayload', 'Packet']

# %% ../nbs/api/00_packet.ipynb 5
import asyncio

import fbdev

# %% ../nbs/api/00_packet.ipynb 7
class NullPayload:
    _instance = None
    def __new__(cls):
        if cls._instance is None:
            cls._instance = super(NullPayload, cls).__new__(cls)
        return cls._instance
    def __repr__(self):
        return "<NullPayload>"

# %% ../nbs/api/00_packet.ipynb 9
class Packet:
    def __init__(self, data):
        self._consumed = False
        self._data = data
        self._dtype = type(data)
            
    @property
    def consumed(self): return self._consumed
    @property
    def is_empty(self): return self._dtype == NullPayload
    @property
    def dtype(self): return self._dtype
        
    @classmethod
    def get_empty(cls):
        return cls(NullPayload())
        
    async def consume(self):
        if self.consumed:
            raise RuntimeError("Packet already consumed.")
        data = self._data
        self._data = None
        self._consumed = True
        return data
    
    def get_deep_copy(self):
        pass
